#!/usr/bin/env bash
# Bash script to install and configure Nginx

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
service nginx reload
