#!/usr/bin/env bash
# Bash script to install and configure Nginx

apt-get update
apt-get install -y nginx
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
chown -R /var/www/html
service nginx restart
