#!/usr/bin/env bash
# Bash script to configure Nginx for redirection to another page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

redirection_string="server_name _;\n\trewrite \/redirect_me https:\/\/google.com permanent;"

sudo sed -i "s/server_name _;/$redirection_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
