#!/usr/bin/env bash
# Bash script to configure Nginx for redirection to another page

apt-get update
apt-get install -y nginx

cat <<EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 404;
    }
}
EOF

ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
unlink /etc/nginx/sites-enabled/default
service nginx restart
