#!/usr/bin/env bash
# Bash script to configure Nginx with a custom 404 page

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root or with sudo."
    exit 1
fi

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
chown -R www-data:www-data /var/www/html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.google.com/;
    }

    # Custom 404 page
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
        default_type "text/html";
        return 404 'Ceci n'est pas une page';
    }
}" > /etc/nginx/sites-available/default

service nginx restart
