#!/usr/bin/env bash
# Bash script to create replica of web-01 and include custom HTTP header

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

redirection_string="server_name _;\n\trewrite \/redirect_me https:\/\/google.com permanent;"

sudo sed -i "s/server_name _;/$redirection_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

error_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$error_string/" /etc/nginx/sites-enabled/default

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
