#!/usr/bin/env bash
# Configuration of HAProxy

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend web_frontend
        bind *:80
        mode http
        default_backend web_backend
backend web_backend
        balance roundrobin
        server 503585-web-01 100.25.148.28:80 check
        server 503585-web-02 52.86.142.5:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
