#!/usr/bin/env bash

# Check for the correct amount of argument
if [ -z "$1" ]; then
  echo "Usage: $0 {start|stop|restart}"
  exit 1
elif [ -n "$2" ]; then
  echo "Usage: $0 {start|stop|restart}"
  exit 1
fi

# Execute the command line arguments
if [ "$1" == "start" ]; then
  if [ -e "/var/run/my_process.pid" ]; then
    echo "Error: manage_my_process is already running. Use '$0 restart' to restart."
    exit 1
  fi
  ./manage_my_process &
  echo $! > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$1" == "stop" ]; then
  if [ -e "/var/run/my_process.pid" ]; then
    pkill -F "/var/run/my_process.pid"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
  else
    echo "Error: manage_my_process is not running."
    exit 1
  fi

elif [ "$1" == "restart" ]; then
  "$0" stop > /dev/null
  "$0" start > /dev/null
  echo "manage_my_process restarted"

else
  echo "Usage: $0 {start|stop|restart}"
  exit 1
fi

