#!/usr/bin/env bash
# Bash script that displays:
#     To infinity and beyond indefinitely
#     With a sleep 2 in between each iteration
#     I am invincible!!! when receiving a SIGTERM signal

trap_sigterm()
{
    echo "I am invicible!!!"
}

i=0
while [ "$i" -eq 0 ]
do
    echo "To infinity and beyond"
    sleep 2
    trap trap_sigterm SIGTERM
done
