#!/usr/bin/env bash
# Safeguards root by using nginx user with less priviledges instead

# Set the nginx user in the nginx configuration
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Replace port 80 with 8080 in the default site configuration
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Set appropriate permissions for the nginx configuration file
sudo chmod 644 /etc/nginx/nginx.conf

# Stop Apache if it's running (assuming pkill is available)
sudo pkill apache2

# Start the nginx service
sudo -u nginx service nginx start
